### ISSUE TITLE
Error during the executin "The system cannot find the file specified"

### ISSUE THREAD

**Issue by tanjaduro** [aquality-automation/aquality-winappdriver-dotnet#42]
I am trying to use aquality-winappdriver-dotnet on my project, but I am getting next error:

>  Message: 
>     OpenQA.Selenium.WebDriverException : The system cannot find the file specified
>   Stack Trace: 
>     RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
>     RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>     AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>     RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
>     RemoteWebDriver.ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
>     RemoteApplicationFactory.CreateSession(Uri driverServerUri, AppiumOptions appliumOptions)
>     ApplicationFactory.GetApplicationSession(Uri driverServerUri)
>     <>c__DisplayClass10_0.<GetApplication>b__0()
>     Application.get_Driver()
>     <.ctor>b__1_0()
>     <>c__DisplayClass6_0.<PerformAction>b__0()
>     <>c__DisplayClass6_0.<DoWithRetry>b__0()
>     ElementActionRetrier.DoWithRetry[T](Func`1 function)
>     ElementActionRetrier.DoWithRetry(Action action)
>     ElementActions.PerformAction(Func`3 action)
>     KeyboardActions.SendKeys(String keySequence, Nullable`1 sendAfterSequence)
>     PatientPage.FillIntoPatientDialog(PatientModel patientModel) line 46
>     MainWorkflowTests.CreateNewPatientManually(PatientModel patientModel) line 104
>     MainWorkflowTests.MainWorkflowTest() line 70

**Comment by mialeska** [comment]
@tdurova Hello there! 
It looks like a configuration problem. Seems that appium cannot find your application executable by the path provided.  
I can guess that you have wrong path to your application in the settings.json file. Could you please share the settings.json file from your project? 
Also, please take a look at our instruction in README.MD and make sure that you have set "Copy always" build option for your settings.json and that the file is located inside the Resources folder in your project.

**Comment by tanjaduro** [comment]
@mialeska is it possible to use several different settings.json files?

Right now I use app.config transformation and I have files like:
App.Remote.Config
App.Local.Config

where I configure the host, port, login, password.
Then in CI I execute:
` - '& "$env:MSBUILD_PATH" /p:Configuration=Remote /clp:ShowCommandLine'

but locally to debug I use "Local" solution configuration.
 
With Aquality framework, I don't understand how to do the same..

**Comment by mialeska** [comment]
Answered to second question here: #43
