### ISSUE TITLE
How to run project with different configurations

### ISSUE THREAD

**Issue by tanjaduro** [aquality-automation/aquality-winappdriver-dotnet#43]
Is it possible to use several different **settings.json** files?

Right now I use app.config transformation and I have files like:
- App.Remote.Config
- App.Local.Config

where I configure the host, port, login, password.
Then in CI I execute:
` - '& "$env:MSBUILD_PATH" /p:Configuration=Remote /clp:ShowCommandLine
`
but locally to debug I use "**Local**" solution configuration.
 
With Aquality framework, I don't understand how to do the same..

**Comment by mialeska** [comment]
Yes it is possible.
You can set "profile" environment variable to achive this.
For example, if "profile" environment variable is set to "local", then the file "settings.local.json" will be used for Aquality services configuration. 
It is implemented at Startup.cs: https://github.com/aquality-automation/aquality-selenium-core-dotnet/blob/master/Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/Startup.cs

**Comment by mialeska** [comment]
You can also override any of variables from setting.json via environment variables.
Please take a look at examples here: https://github.com/aquality-automation/aquality-selenium-core-dotnet/blob/master/Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/JsonFileTests.cs
